version: "3.8"
services:
    microblog:
      build: .
      container_name: microblogs
      ports:
        - "8000:5000"
      networks:
        - elastic
      depends_on:
        - elasticsearch
        - mysql
        - redis
      environment:
        - SECRET_KEY=my-secret-key
        - MAIL_SERVER=smtp.googlemail.com
        - MAIL_PORT=587
        - MAIL_USE_TLS=true
        - MAIL_USERNAME=$MAIL_USERNAME
        - MAIL_PASSWORD=$MAIL_PASSWORD
        - ELASTICSEARCH_URL=https://elasticsearch:9200
        - ELASTICSEARCH_LOGIN=elastic
        - ELASTICSEARCH_PASSWORD=evUIZakvL56r1fLXudt4
        - ADMINS=$ADMINS
        - REDIS_URL=redis://redis:6379/0
        - DATABASE_URL=mysql+pymysql://microblog:Mysql12404@mysql/microblog
      links:
        - mysql
        - redis
        - elasticsearch

    worker:
      build: .
      container_name: rq-workers
      networks:
        - elastic
      depends_on:
        - elasticsearch
        - mysql
        - redis
        - microblog
      environment:
        - SECRET_KEY=my-secret-key
        - MAIL_SERVER=smtp.googlemail.com
        - MAIL_PORT=587
        - MAIL_USE_TLS=true
        - MAIL_USERNAME=$MAIL_USERNAME
        - MAIL_PASSWORD=$MAIL_PASSWORD
        - ELASTICSEARCH_URL=https://elasticsearch:9200
        - ELASTICSEARCH_LOGIN=elastic
        - ELASTICSEARCH_PASSWORD=evUIZakvL56r1fLXudt4
        - ADMINS=$ADMINS
        - DATABASE_URL=mysql+pymysql://microblog:Mysql12404@mysql/microblog
        - REDIS_URL=redis://redis:6379/0
      links:
        - mysql
        - redis
      entrypoint: venv/bin/rq worker --url redis://redis:6379/0 microblog-tasks

    redis:
      image: redis
      container_name: redis
      ports:
        - "6379:6379"
      networks:
        - elastic

    elasticsearch:
      container_name: elasticsearchs
      image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
      ports:
        - "9200:9200"
        - "9300:9300"
      networks:
        - elastic
      environment:
        - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

    mysql:
      container_name: mysql
      image: mysql/mysql-server
      restart: always
      networks:
        - elastic
      environment:
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
        - MYSQL_DATABASE=microblog
        - MYSQL_USER=microblog
        - MYSQL_PASSWORD=Mysql12404



networks:
  elastic: {}
