version: "3.8"
services:
    muse_me:
      build: .
      container_name: muse_me
      ports:
        - "8000:5000"
      networks:
        - elastic
      depends_on:
        - elasticsearch
        - mysql
        - redis
      environment:
        - SECRET_KEY=${SECRET_KEY}
        - MAIL_SERVER=smtp.googlemail.com
        - MAIL_PORT=587
        - MAIL_USE_TLS=true
        - MAIL_USERNAME=$MAIL_USERNAME
        - MAIL_PASSWORD=$MAIL_PASSWORD
        - ELASTICSEARCH_URL=https://elasticsearch:9200
        - ELASTICSEARCH_LOGIN=elastic
        - ELASTICSEARCH_PASSWORD=evUIZakvL56r1fLXudt4
        - ADMINS=$ADMINS
        - REDIS_URL=redis://redis:6379/0
        - DATABASE_URL=mysql+pymysql://muse_me:Mysql12404@mysql/muse_me
      links:
        - mysql
        - redis
        - elasticsearch

    worker:
      build: .
      container_name: rq-workers
      networks:
        - elastic
      depends_on:
        - elasticsearch
        - mysql
        - redis
        - muse_me
      environment:
        - SECRET_KEY=${SECRET_KEY}
        - MAIL_SERVER=smtp.googlemail.com
        - MAIL_PORT=587
        - MAIL_USE_TLS=true
        - MAIL_USERNAME=$MAIL_USERNAME
        - MAIL_PASSWORD=$MAIL_PASSWORD
        - ELASTICSEARCH_URL=https://elasticsearch:9200
        - ELASTICSEARCH_LOGIN=elastic
        - ELASTICSEARCH_PASSWORD=evUIZakvL56r1fLXudt4
        - ADMINS=$ADMINS
        - DATABASE_URL=mysql+pymysql://muse_me:Mysql12404@mysql/muse_me
        - REDIS_URL=redis://redis:6379/0
      links:
        - mysql
        - redis
      entrypoint: venv/bin/rq worker --url redis://redis:6379/0 muse_me-tasks

    redis:
      image: redis
      container_name: redis
      ports:
        - "6379:6379"
      networks:
        - elastic

    elasticsearch:
      container_name: elasticsearch
      image: elasticsearch:8.7.0
      restart: always
      ports:
        - "9200:9200"
        - "9300:9300"
      networks:
        - elastic
      environment:
        - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      volumes:
        - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml


    mysql:
      container_name: mysql
      image: mysql/mysql-server
      restart: always
      networks:
        - elastic
      environment:
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
        - MYSQL_DATABASE=muse_me
        - MYSQL_USER=muse_me
        - MYSQL_PASSWORD=Mysql12404



networks:
  elastic: {}
