version: "3.9"
services:
    muse_me:
      build: .
      container_name: muse_me
      ports:
        - "8000:5000"
      networks:
        - elastic
      depends_on:
        - elasticsearch
        - mysql
        - redis
      env_file:
        - .env
        - .flaskenv


    worker:
      build: .
      container_name: rq-workers
      networks:
        - elastic
      depends_on:
        - elasticsearch
        - mysql
        - redis
        - muse_me
      env_file:
        - .env
        - .flaskenv
      entrypoint: venv/bin/rq worker --url redis://redis:6379/0 muse_me-tasks

    redis:
      image: redis
      container_name: redis
      ports:
        - "6379:6379"
      networks:
        - elastic

    elasticsearch:
      container_name: elasticsearch
      image: elasticsearch:8.7.0
      restart: always
      ports:
        - "9200:9200"
        - "9300:9300"
      networks:
        - elastic
      environment:
        - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      volumes:
        - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml


    mysql:
      container_name: mysql
      image: mysql/mysql-server
      restart: always
      networks:
        - elastic
      environment:
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
        - MYSQL_DATABASE=muse_me
        - MYSQL_USER=muse_me
        - MYSQL_PASSWORD=Mysql12404



networks:
  elastic: {}
