version: "3.9"
services:
    muse_me:
      build: .
      container_name: muse_me
      volumes:
        - ./app/static:/app/static
      networks:
        - elastic
      depends_on:
        - elasticsearch
        - mysql
        - redis
      env_file:
        - .env
        - .flaskenv

    worker:
      build: .
      container_name: rq-workers
      networks:
        - elastic
      depends_on:
        - elasticsearch
        - mysql
        - redis
        - muse_me
      env_file:
        - .env
        - .flaskenv
      entrypoint: venv/bin/rq worker --url redis://redis:6379/0 muse_me-tasks

    nginx:
      image: nginx:latest
      container_name: nginx
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./app/static:/app/static
      depends_on:
        - muse_me
      networks:
        - elastic

    redis:
      image: redis
      container_name: redis

      networks:
        - elastic

    elasticsearch:
      container_name: elasticsearch
      image: elasticsearch:8.7.0

      networks:
        - elastic
      environment:
        - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      volumes:
        - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml


    mysql:
      container_name: mysql
      image: mysql/mysql-server
      restart: always
      networks:
        - elastic
      environment:
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
        - MYSQL_DATABASE=muse_me
        - MYSQL_USER=muse_me
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}



networks:
  elastic: {}
