"""empty message

Revision ID: 8485b47b202b
Revises: 7c1ec8405643
Create Date: 2023-03-18 19:36:58.931504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8485b47b202b'
down_revision = '7c1ec8405643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image_path')
    # ### end Alembic commands ###
