"""empty message

Revision ID: a4ce8d7c62a5
Revises: 9570f3e4975a
Create Date: 2023-03-30 13:13:30.985122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4ce8d7c62a5'
down_revision = '9570f3e4975a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reactions', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reactions', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reactions', type_='foreignkey')
    op.drop_column('reactions', 'image_id')
    # ### end Alembic commands ###
