"""empty message

Revision ID: a5a848269d0d
Revises: 92f6c008a169
Create Date: 2023-04-01 23:14:34.641766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a848269d0d'
down_revision = '92f6c008a169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('background_image', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'background_image')
    # ### end Alembic commands ###
